Add mobile-desktop version
hamzaw9/capstone-project-1 pull request #1
Opened 2023-08-01 18:35 UTC by hamzaw9

In this pull request:

### Home Page:

- Created a header with a navigation bar and social media links.
- Created a dynamic "Leading Instructors" section.
- Added a main section with event details and a call-to-action button.
- Included a "Feature Courses" section showcasing different courses.
- Designed a "Partner" section displaying partner logos.
- Implemented a footer with the ITMinds logo and copyright information.

### About Page:

- Created a header with a navigation bar and social media links.
- Added a main section with event details and contact information.
- Included an "ITMinds Aim" section describing the organization's mission.
- Implemented a "See Previous Events" section with images and years of past events.
- Designed a "Partner" section displaying partner logos.
- Included a footer with the ITMinds logo and copyright information.

2023-08-01 19:35 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @hamzaw9, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Great UI. :heavy_check_mark: 
-  Clean and clear codebase. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 19:35 UTC, Qoosim commented on README.md
> +
- [ ] KIndly look into this live demo link. It is not working properly. Below screenshot is what I got while opened the link.

### Live Demo Display

![live-demo](https://github.com/hamzaw9/capstone-project-1/assets/26597432/ef73bf25-bfeb-47a9-9f2c-bb158749d246)

2023-08-01 19:35 UTC, Qoosim commented on index.html
> +    </footer>
- [ ] Kindly reduce the padding top and bottom for this two sections. The parnter and the footer sections in order to match the guiding template. The content of your footer is not as plenty as what we have on the guiding template. Too much padding top and botton for this part is not necessary. Kindly reduce it with that of partner too. I understand that you're trying to make it to look exactly like guiding template which is what is expected from you. But that is too much in this regard. Kindly do just that.
- [ ] You're expected to produce a close replica of the design. This includes. font, color among others. Kindly reduce the opacity of the background color of your partner section so as to match the giving design. Your background color is too dark compare to the guiding temp. Kindly address that too.

### Your Design
![your-footer-home](https://github.com/hamzaw9/capstone-project-1/assets/26597432/f8e05693-ee4a-4cd1-a560-a43b22ea67c6)

### Guiding Template
![temp-footer-home](https://github.com/hamzaw9/capstone-project-1/assets/26597432/0699e4b6-1c79-4eb0-881f-870ceec03ded)

2023-08-01 19:35 UTC, Qoosim commented on about.html
> +      <div class="event-inner">
- [ ] KIndly change the dividing line color to the template color as to match the guiging template as required by the project requirements.
- [ ] Do not forget to change the color of `See Previous Event` to the color on the guiding template. This is to train ourselves on how to clients requests to the letter.

### Your Design
![your-connect-line](https://github.com/hamzaw9/capstone-project-1/assets/26597432/0173c148-725a-43cf-b86d-23a605a55423)

### Guiding Template
![temp-connect-line](https://github.com/hamzaw9/capstone-project-1/assets/26597432/91be9a66-bc25-43af-9374-9ca7e311289b)

2023-08-01 19:35 UTC, Qoosim commented on index.html
> +          <img src="images/program_icon_01.png" />
- [ ] I would like to recommend you to always include `alt` attribute inside you `img`  tag with appropriate text to help vision impaired readers. Kindly check other sections where the `img` tag is used and include the `alt` attribute as needed.

2023-08-01 19:35 UTC, Qoosim commented on index.html
> +        </div>-->
- [ ] Let's always remove commented code. It does not make our codebase to look clean. Kindly remove this.

2023-08-02 11:14 UTC, Ismailco approved these changes
### Hi @hamzaw9, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️ No linter errors
✔️ Used GitHub Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 11:35 UTC, merged